export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_SELECTEDPLAYLIST: "SET_SELECTEDPLAYLIST",
  SET_SELECTEDPLAYLISTDATA: "SET_SELECTEDPLAYLISTDATA",
  SET_SELECTEDTRACK:"SET_SELECTEDTRACK",
  SET_PLAYERSTATE: "SET_PLAYERSTATE"
}